### **Project 1** - San Diego Gas Prices
#### Vanessa Dumlao, Shruti Palur Mallampalli, Noelle Watson

In [1]:
# Dependencies and Setup
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
from config import numbeo_api

In [2]:
# Pull in gas prices csv
gas_prices_data = pd.read_csv("Resources/gas-prices_2023-10-02.csv")
gas_prices_data.head()

,title,address,gasPrices/0/currency,gasPrices/0/gasType,gasPrices/0/price,gasPrices/0/priceTag,gasPrices/0/unit,gasPrices/0/updatedAt,gasPrices/1/currency,gasPrices/1/gasType,...,gasPrices/3/updatedAt,website,phone,totalScore,rank,reviewsCount,isAdvertisement,categoryName,searchString,url
0,Fashion Valley Gas,"6899 Friars Rd, San Diego, CA 92108",USD,Regular,6.40,$6.40,gallon,2023-10-02T08:50:29.000Z,USD,Midgrade,...,NaN,NaN,(619) 295-1169,4.2,2,136,False,Gas station,gas station in San Diego,https://www.google.com/maps/place/Fashion+Vall...
1,Shell,"2777 Health Center Dr, San Diego, CA 92123",USD,Regular,7.01,$7.01,gallon,2023-10-02T11:26:11.000Z,USD,Midgrade,...,2023-10-01T00:30:12.000Z,https://find.shell.com/us/fuel/12476277-2777-h...,(859) 279-3673,3.5,3,40,False,Gas station,gas station in San Diego,https://www.google.com/maps/place/Shell/@32.79...
2,Mobil,"10496 Clairemont Mesa Blvd, San Diego, CA 92124",USD,Regular,6.00,$6.00,gallon,2023-10-02T13:00:11.000Z,USD,Midgrade,...,2023-10-02T10:05:01.000Z,https://www.exxon.com/en/find-station/MOBIL-SA...,(858) 565-1627,4.3,7,65,False,Gas station,gas station in San Diego,https://www.google.com/maps/place/Mobil/@32.82...
3,Shell,"2521 Pacific Hwy, San Diego, CA 92101",USD,Regular,7.00,$7.00,gallon,2023-10-02T15:21:32.000Z,USD,Midgrade,...,NaN,https://find.shell.com/us/fuel/10008237-2521-p...,(619) 233-4120,3.3,8,94,False,Gas station,gas station in San Diego,https://www.google.com/maps/place/Shell/@32.72...
4,Shell,"3901 Governor Dr, San Diego, CA 92122",USD,Regular,6.30,$6.30,gallon,2023-10-02T07:57:52.000Z,USD,Midgrade,...,NaN,https://find.shell.com/us/fuel/10087441-3901-g...,(858) 453-0676,3.3,20,44,False,Gas station,gas station in San Diego,https://www.google.com/maps/place/Shell/@32.85...

In [3]:
# Parse out zip code
gas_prices_data['zip code'] = gas_prices_data['address'].str.split().str[-1]
gas_prices_data.head()

,title,address,gasPrices/0/currency,gasPrices/0/gasType,gasPrices/0/price,gasPrices/0/priceTag,gasPrices/0/unit,gasPrices/0/updatedAt,gasPrices/1/currency,gasPrices/1/gasType,...,website,phone,totalScore,rank,reviewsCount,isAdvertisement,categoryName,searchString,url,zip code
0,Fashion Valley Gas,"6899 Friars Rd, San Diego, CA 92108",USD,Regular,6.40,$6.40,gallon,2023-10-02T08:50:29.000Z,USD,Midgrade,...,NaN,(619) 295-1169,4.2,2,136,False,Gas station,gas station in San Diego,https://www.google.com/maps/place/Fashion+Vall...,92108
1,Shell,"2777 Health Center Dr, San Diego, CA 92123",USD,Regular,7.01,$7.01,gallon,2023-10-02T11:26:11.000Z,USD,Midgrade,...,https://find.shell.com/us/fuel/12476277-2777-h...,(859) 279-3673,3.5,3,40,False,Gas station,gas station in San Diego,https://www.google.com/maps/place/Shell/@32.79...,92123
2,Mobil,"10496 Clairemont Mesa Blvd, San Diego, CA 92124",USD,Regular,6.00,$6.00,gallon,2023-10-02T13:00:11.000Z,USD,Midgrade,...,https://www.exxon.com/en/find-station/MOBIL-SA...,(858) 565-1627,4.3,7,65,False,Gas station,gas station in San Diego,https://www.google.com/maps/place/Mobil/@32.82...,92124
3,Shell,"2521 Pacific Hwy, San Diego, CA 92101",USD,Regular,7.00,$7.00,gallon,2023-10-02T15:21:32.000Z,USD,Midgrade,...,https://find.shell.com/us/fuel/10008237-2521-p...,(619) 233-4120,3.3,8,94,False,Gas station,gas station in San Diego,https://www.google.com/maps/place/Shell/@32.72...,92101
4,Shell,"3901 Governor Dr, San Diego, CA 92122",USD,Regular,6.30,$6.30,gallon,2023-10-02T07:57:52.000Z,USD,Midgrade,...,https://find.shell.com/us/fuel/10087441-3901-g...,(858) 453-0676,3.3,20,44,False,Gas station,gas station in San Diego,https://www.google.com/maps/place/Shell/@32.85...,92122

In [4]:
# Rename Columns
gas_prices_data_df = gas_prices_data.rename(columns={"title" : "business",
                                "gasPrices/0/currency" : "gas1 currency",
                                "gasPrices/0/gasType" : "gas1 type",
                                "gasPrices/0/price": "gas1 price",
                                "gasPrices/0/priceTag" : "gas1 pricetag",
                                "gasPrices/0/unit": "gas1 unit",
                                "gasPrices/0/updatedAt" : "gas1 updated",
                                "gasPrices/1/currency" : "gas2 currency",
                                "gasPrices/1/gasType": "gas2 type",
                                "gasPrices/1/price": "gas2 price",
                                "gasPrices/1/priceTag": "gas2 pricetag",
                                "gasPrices/1/unit": "gas2 unit",
                                "gasPrices/1/updatedAt" : "gas2 updated",
                                "gasPrices/2/currency" : "gas3 currency",
                                "gasPrices/2/gasType": "gas3 type",
                                "gasPrices/2/price": "gas3 price",
                                "gasPrices/2/priceTag": "gas3 pricetag",
                                "gasPrices/2/unit": "gas3 unit",
                                "gasPrices/2/updatedAt": "gas3 updated",
                                "gasPrices/3/currency": "gas4 currency",
                                "gasPrices/3/gasType": "gas4 type",
                                "gasPrices/3/price": "gas4 price",
                                "gasPrices/3/priceTag": "gas4 pricetag",
                                "gasPrices/3/unit" :"gas4 unit",
                                "gasPrices/3/updatedAt" : "gas4 updated"
    
})

In [5]:
gas_prices_data_df.head()

,business,address,gas1 currency,gas1 type,gas1 price,gas1 pricetag,gas1 unit,gas1 updated,gas2 currency,gas2 type,...,website,phone,totalScore,rank,reviewsCount,isAdvertisement,categoryName,searchString,url,zip code
0,Fashion Valley Gas,"6899 Friars Rd, San Diego, CA 92108",USD,Regular,6.40,$6.40,gallon,2023-10-02T08:50:29.000Z,USD,Midgrade,...,NaN,(619) 295-1169,4.2,2,136,False,Gas station,gas station in San Diego,https://www.google.com/maps/place/Fashion+Vall...,92108
1,Shell,"2777 Health Center Dr, San Diego, CA 92123",USD,Regular,7.01,$7.01,gallon,2023-10-02T11:26:11.000Z,USD,Midgrade,...,https://find.shell.com/us/fuel/12476277-2777-h...,(859) 279-3673,3.5,3,40,False,Gas station,gas station in San Diego,https://www.google.com/maps/place/Shell/@32.79...,92123
2,Mobil,"10496 Clairemont Mesa Blvd, San Diego, CA 92124",USD,Regular,6.00,$6.00,gallon,2023-10-02T13:00:11.000Z,USD,Midgrade,...,https://www.exxon.com/en/find-station/MOBIL-SA...,(858) 565-1627,4.3,7,65,False,Gas station,gas station in San Diego,https://www.google.com/maps/place/Mobil/@32.82...,92124
3,Shell,"2521 Pacific Hwy, San Diego, CA 92101",USD,Regular,7.00,$7.00,gallon,2023-10-02T15:21:32.000Z,USD,Midgrade,...,https://find.shell.com/us/fuel/10008237-2521-p...,(619) 233-4120,3.3,8,94,False,Gas station,gas station in San Diego,https://www.google.com/maps/place/Shell/@32.72...,92101
4,Shell,"3901 Governor Dr, San Diego, CA 92122",USD,Regular,6.30,$6.30,gallon,2023-10-02T07:57:52.000Z,USD,Midgrade,...,https://find.shell.com/us/fuel/10087441-3901-g...,(858) 453-0676,3.3,20,44,False,Gas station,gas station in San Diego,https://www.google.com/maps/place/Shell/@32.85...,92122

In [6]:
gas_prices_data_df.columns.tolist()

['business',
 'address',
 'gas1 currency',
 'gas1 type',
 'gas1 price',
 'gas1 pricetag',
 'gas1 unit',
 'gas1 updated',
 'gas2 currency',
 'gas2 type',
 'gas2 price',
 'gas2 pricetag',
 'gas2 unit',
 'gas2 updated',
 'gas3 currency',
 'gas3 type',
 'gas3 price',
 'gas3 pricetag',
 'gas3 unit',
 'gas3 updated',
 'gas4 currency',
 'gas4 type',
 'gas4 price',
 'gas4 pricetag',
 'gas4 unit',
 'gas4 updated',
 'website',
 'phone',
 'totalScore',
 'rank',
 'reviewsCount',
 'isAdvertisement',
 'categoryName',
 'searchString',
 'url',
 'zip code']

In [7]:
cleaned_gas_df = gas_prices_data_df[["business", "zip code", "address", "gas1 currency", "gas1 type", "gas1 price", "gas1 pricetag", "gas1 unit", "gas1 updated",
                                    "gas2 currency", "gas2 type", "gas2 price", "gas2 pricetag", "gas2 unit", "gas2 updated",
                                    "gas3 currency", "gas3 type", "gas3 price", "gas3 pricetag", "gas3 unit", "gas3 updated"]].copy()

In [8]:
cleaned_gas_df.head()

,business,zip code,address,gas1 currency,gas1 type,gas1 price,gas1 pricetag,gas1 unit,gas1 updated,gas2 currency,...,gas2 price,gas2 pricetag,gas2 unit,gas2 updated,gas3 currency,gas3 type,gas3 price,gas3 pricetag,gas3 unit,gas3 updated
0,Fashion Valley Gas,92108,"6899 Friars Rd, San Diego, CA 92108",USD,Regular,6.40,$6.40,gallon,2023-10-02T08:50:29.000Z,USD,...,6.5,$6.50,gallon,2023-10-01T18:08:43.000Z,USD,Premium,6.60,$6.60,gallon,2023-09-30T16:48:07.000Z
1,Shell,92123,"2777 Health Center Dr, San Diego, CA 92123",USD,Regular,7.01,$7.01,gallon,2023-10-02T11:26:11.000Z,USD,...,7.2,$7.20,gallon,2023-10-02T12:03:22.000Z,USD,Premium,6.60,$6.60,gallon,2023-10-02T09:14:17.000Z
2,Mobil,92124,"10496 Clairemont Mesa Blvd, San Diego, CA 92124",USD,Regular,6.00,$6.00,gallon,2023-10-02T13:00:11.000Z,USD,...,6.4,$6.40,gallon,2023-10-01T13:35:00.000Z,USD,Premium,6.40,$6.40,gallon,2023-10-02T09:19:29.000Z
3,Shell,92101,"2521 Pacific Hwy, San Diego, CA 92101",USD,Regular,7.00,$7.00,gallon,2023-10-02T15:21:32.000Z,USD,...,7.2,$7.20,gallon,2023-09-30T10:30:08.000Z,USD,Premium,7.30,$7.30,gallon,2023-10-02T15:17:31.000Z
4,Shell,92122,"3901 Governor Dr, San Diego, CA 92122",USD,Regular,6.30,$6.30,gallon,2023-10-02T07:57:52.000Z,USD,...,6.5,$6.50,gallon,2023-10-01T15:11:50.000Z,USD,Premium,6.66,$6.66,gallon,2023-10-02T07:24:18.000Z

In [9]:
cleaned_gas_df.count()

business         102
zip code         102
address          102
gas1 currency     85
gas1 type         85
gas1 price        85
gas1 pricetag     85
gas1 unit         85
gas1 updated      85
gas2 currency     85
gas2 type         85
gas2 price        85
gas2 pricetag     85
gas2 unit         85
gas2 updated      85
gas3 currency     85
gas3 type         85
gas3 price        85
gas3 pricetag     85
gas3 unit         85
gas3 updated      85
dtype: int64

In [10]:
extra_clean_gas = cleaned_gas_df.dropna()
extra_clean_gas.count()

business         85
zip code         85
address          85
gas1 currency    85
gas1 type        85
gas1 price       85
gas1 pricetag    85
gas1 unit        85
gas1 updated     85
gas2 currency    85
gas2 type        85
gas2 price       85
gas2 pricetag    85
gas2 unit        85
gas2 updated     85
gas3 currency    85
gas3 type        85
gas3 price       85
gas3 pricetag    85
gas3 unit        85
gas3 updated     85
dtype: int64

In [11]:
print(extra_clean_gas['gas1 currency'].unique())
print(extra_clean_gas['gas1 type'].unique())
print(extra_clean_gas['gas1 unit'].unique())
print(extra_clean_gas['gas2 currency'].unique())
print(extra_clean_gas['gas2 type'].unique())
print(extra_clean_gas['gas2 unit'].unique())
print(extra_clean_gas['gas3 currency'].unique())
print(extra_clean_gas['gas3 type'].unique())
print(extra_clean_gas['gas3 unit'].unique())

['USD']
['Regular']
['gallon']
['USD']
['Midgrade']
['gallon']
['USD']
['Premium']
['gallon']

In [12]:
# Read in CSV and clean data
SD_median_income = pd.read_csv("Resources/Household Income Median.csv")
SD_median_income = SD_median_income.rename(columns={'Zip':'zip code'})
SD_median_income = SD_median_income.dropna()
SD_median_income.head()

  zip code  Household Income Median
0    92014                 155531.0
1    92025                  58273.0
2    92027                  65989.0
3    92037                 109194.0
4    92071                  87334.0

In [13]:
# Find unique number of zipcodes in income dataset
SD_median_income['zip code'].unique().size

37

In [14]:
# Find unique number of zipcodes in gas dataset
extra_clean_gas['zip code'].unique().size

23

In [15]:
# Calculate average gas prices per zip code
averaged_gas1_prices = extra_clean_gas.groupby(["zip code"])["gas1 price"].mean()
averaged_gas2_prices = extra_clean_gas.groupby(["zip code"])["gas2 price"].mean()
averaged_gas3_prices = extra_clean_gas.groupby(["zip code"])["gas3 price"].mean()

In [16]:
# Create df with avg gas prices per zip
gas_price_per_zip_avg = pd.DataFrame(
    {
        "gas1 mean price": averaged_gas1_prices,
        "gas2 mean price": averaged_gas2_prices,
        "gas3 mean price": averaged_gas3_prices,
    }
)
gas_price_per_zip_avg.head()

          gas1 mean price  gas2 mean price  gas3 mean price
zip code
92101            6.733333         6.900000         6.950000
92102            6.400000         6.600000         6.725000
92103            6.640000         6.860000         6.980000
92104            6.376667         6.560000         6.758889
92105            6.293333         6.418333         6.671667

In [37]:
# Load in csv with lat, long, population, density
zip_df = pd.read_csv("Resources/uszips.csv")
sd_zip_df_unclean = zip_df.loc[zip_df["county_names_all"] == "San Diego", :]
sd_zip_df_unclean = sd_zip_df_unclean.rename(columns={'zip':'zip code'})
# Create df of only info we want
sd_zip_df = sd_zip_df_unclean[['zip code', 'lat', 'lng', 'city', 'population', 'density']]
sd_zip_df = pd.DataFrame(sd_zip_df)
sd_zip_df = sd_zip_df.set_index('zip code')
sd_zip_df.head(sd_zip_df)

TypeError: cannot do positional indexing on Index with these indexers [               lat        lng         city  population  density
zip code
91901     32.81467 -116.71929       Alpine     18367.0     91.1
91902     32.67479 -117.00475       Bonita     17759.0    611.3
91905     32.67773 -116.30734    Boulevard      1616.0      7.5
91906     32.66241 -116.47255        Campo      4547.0     16.7
91910     32.63653 -117.06301  Chula Vista     76291.0   2340.3
...            ...        ...          ...         ...      ...
92155     32.67148 -117.16714    San Diego       340.0    334.1
92161     32.87420 -117.23159    San Diego         0.0      0.0
92173     32.55552 -117.05114   San Ysidro     29634.0   3976.4
92179     32.58409 -116.93349    San Diego      4061.0   6268.8
92182     32.77498 -117.07424    San Diego         0.0      0.0

[112 rows x 5 columns]] of type DataFrame

In [36]:
merg_zip_data = pd.merge(sd_zip_df, gas_price_per_zip_avg, on='zip code')

ValueError: You are trying to merge on int64 and object columns. If you wish to proceed you should use pd.concat